In [1]:
import networkx as nx
import generator as gen
import simulate as sim
import conComp as cc
import random
import numpy as np


In [5]:
for i in range(50):
    g = gen.graph_gen(2,50,0.2,0.02)
    dev = [0.1] + [0.5] * 3
    std_devs = [dev, dev]
    changeVec = [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
    cmat = gen.culture_init(g, std_devs, changeVec)
    g, culturemat = sim.simulate_iterstop(g,cmat)

In [5]:
for x,y in 
    '''if x <= 0:
        x = 0.01
    elif x >= 1:
        x = 0.99'''

[0.34248626 0.63557844 0.68670731]
[0.88819908 0.66338217 0.47330252]
[-0.16995431  0.44105915  0.50929792]
[0.12845474 0.08337327 0.14972978]
[0.3136984  0.54252199 0.34122159]
[ 1.56222766 -0.42493738  0.8184649 ]
[0.63895175 0.21293602 1.29289778]
[-0.14227055  0.05476204  0.41159859]
[0.49433938 0.1406626  0.3128286 ]
[0.69744862 0.65212043 0.26711759]
[0.50295103 1.16153475 0.93971089]
[0.13872273 0.18063694 0.34298067]
[ 0.32212356 -1.03673997  0.16002607]
[-0.16677254  0.43904728  1.03403919]
[-0.38708991  0.77822149 -0.0452398 ]
[-0.00193655  0.67873568  1.39526283]
[1.51825571 0.84152974 0.17794941]
[0.98243576 1.20650969 0.62216208]
[ 0.50096006  0.56888088 -0.01394837]
[0.68973534 0.05241691 0.10550769]
[ 1.15532655  1.16749766 -0.20450563]
[0.79752765 0.5316158  0.7950489 ]
[1.35646345 0.39139759 1.25016868]
[ 0.9164785   0.70095736 -0.04461048]
[0.75591005 1.24358733 0.51128282]
[ 0.57344425  0.20492856 -0.03799839]
[ 1.26231341 -0.17535845 -0.31556013]
[-0.55870307  0.960

In [10]:
d = 0.1
z = 10000/d
0.5 ** z
c = cmat[0]
print(c)
print(c[-3])

[ 1.21859725e+00  5.07581468e-01  6.52044725e-01  1.03739330e+00
 -5.96342238e-01 -7.12557149e-01  3.66724132e-01 -1.74839086e+00
 -1.74131193e-03 -8.79574509e-02  8.48995899e-01 -2.47845641e-02
  1.17318229e-01]
0.8489958985059245


In [4]:
print(l)

[0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
